# Docker Compose file for the Instagram-like application
services: 
  mongodb:
    image: mongo:latest
    container_name: instaflux
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=instaflux
      - MONGO_INITDB_ROOT_PASSWORD=ZER0SEV7N
      - MONGO_INITDB_DATABASE=instaflux
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: 